services:
  - type: web
    name: rcb-universe-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://Pratik:Pratik9890@cluster0.ezqyayl.mongodb.net/rcb_universe?retryWrites=true&w=majority&appName=Cluster0
      - key: PORT
        value: 5000
